# Generated by Django 2.1.7 on 2019-06-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takmyo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='/static/image/unknown.png', null=True, upload_to='profileImage/'),
        ),
    ]
