# Generated by Django 2.1.7 on 2019-06-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takmyo_app', '0006_user_post_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='post_code',
            new_name='postcode',
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('form', 'Form'), ('review', 'Review')], max_length=30, null=True),
        ),
    ]
