# Generated by Django 2.1.7 on 2019-06-22 22:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('takmyo_app', '0009_auto_20190622_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catsitter_promotion_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_image', models.ImageField(blank=True, default='unknown.png', null=True, upload_to='catsiiter_promotionImage/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='catsitter',
            options={'ordering': ['-register_date']},
        ),
        migrations.AddField(
            model_name='catsitter',
            name='available_region',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='catsitter',
            name='available_weekday_am',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='catsitter',
            name='available_weekday_pm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='catsitter',
            name='available_weekend_am',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='catsitter',
            name='care_experience',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='catsitter',
            name='catsitter_profile_image',
            field=models.ImageField(blank=True, default='unknown.png', null=True, upload_to='catsiiter_profileImage/'),
        ),
        migrations.AddField(
            model_name='catsitter',
            name='consignment_price_per_extra_cat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='catsitter',
            name='consignment_price_per_one_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='catsitter',
            name='consignment_price_per_one_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='catsitter',
            name='consignment_price_per_one_week',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='catsitter',
            name='introduce',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='catsitter',
            name='name',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='catsitter',
            name='register_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catsitter',
            name='visit_price_per_extra_cat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='catsitter',
            name='visit_price_per_once',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='catsitter',
            name='warning',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('form', 'Form'), ('review', 'Review')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='catsitter_promotion_image',
            name='catsitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catsiiter_promotion_image', to='takmyo_app.Catsitter'),
        ),
    ]
