# Generated by Django 2.1.7 on 2019-06-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takmyo_app', '0010_auto_20190622_2222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catsitter',
            old_name='available_weekday_am',
            new_name='activation',
        ),
        migrations.RenameField(
            model_name='catsitter',
            old_name='available_weekday_pm',
            new_name='available_identification',
        ),
        migrations.RenameField(
            model_name='catsitter',
            old_name='available_weekend_am',
            new_name='have_care_experience',
        ),
        migrations.RemoveField(
            model_name='catsitter',
            name='care_experience',
        ),
        migrations.AddField(
            model_name='catsitter',
            name='available_day',
            field=models.CharField(choices=[('weekend', 'Weekend'), ('both', 'Both'), ('weekday', 'Weekday')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='catsitter',
            name='available_place',
            field=models.CharField(choices=[('both', 'Both'), ('visit', 'Visit'), ('consignment', 'Consignment')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='catsitter',
            name='available_weekday_time',
            field=models.CharField(choices=[('am', 'Am'), ('both', 'Both'), ('pm', 'Pm')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='catsitter',
            name='available_weekend_time',
            field=models.CharField(choices=[('am', 'Am'), ('both', 'Both'), ('pm', 'Pm')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('review', 'Review'), ('form', 'Form')], max_length=30, null=True),
        ),
    ]
