# Generated by Django 2.1.7 on 2019-06-26 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('takmyo_app', '0011_auto_20190623_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catsitter',
            old_name='rate',
            new_name='rate_per_five',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Ing',
            new_name='lng',
        ),
        migrations.RemoveField(
            model_name='catsitter',
            name='available_consignment',
        ),
        migrations.RemoveField(
            model_name='catsitter',
            name='available_visit',
        ),
        migrations.AddField(
            model_name='catsitter',
            name='rate_per_hundred',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='catsitter',
            name='available_day',
            field=models.CharField(choices=[('both', 'Both'), ('weekday', 'Weekday'), ('weekend', 'Weekend')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='catsitter',
            name='available_weekday_time',
            field=models.CharField(choices=[('both', 'Both'), ('pm', 'Pm'), ('am', 'Am')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='catsitter',
            name='available_weekend_time',
            field=models.CharField(choices=[('both', 'Both'), ('pm', 'Pm'), ('am', 'Am')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='catsitter',
            name='catsitter_profile_image',
            field=models.ImageField(default='unknown_icon.png', upload_to='catsitter_profileImage/'),
        ),
        migrations.AlterField(
            model_name='catsitter_promotion_image',
            name='catsitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catsitter_promotion_image', to='takmyo_app.Catsitter'),
        ),
        migrations.AlterField(
            model_name='catsitter_promotion_image',
            name='promotion_image',
            field=models.ImageField(default='unknown_icon.png', upload_to='catsitter_promotionImage/'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('form', 'Form'), ('review', 'Review')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='detail_address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='extra_address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='unknown_icon.png', null=True, upload_to='profileImage/'),
        ),
    ]
