# Generated by Django 2.1.7 on 2019-06-26 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takmyo_app', '0012_auto_20190626_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catsitter',
            name='available_day',
            field=models.CharField(choices=[('weekend', 'Weekend'), ('weekday', 'Weekday'), ('both', 'Both')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='catsitter',
            name='available_weekday_time',
            field=models.CharField(choices=[('pm', 'Pm'), ('am', 'Am'), ('both', 'Both')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='catsitter',
            name='available_weekend_time',
            field=models.CharField(choices=[('pm', 'Pm'), ('am', 'Am'), ('both', 'Both')], default='', max_length=10),
        ),
    ]
