# Generated by Django 2.1.7 on 2019-06-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takmyo_app', '0014_auto_20190626_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='catsitter',
            name='available_change_consignment_price_per_extra_cat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='catsitter',
            name='available_change_visit_price_per_extra_cat',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='catsitter',
            name='available_day',
            field=models.CharField(choices=[('weekend', 'Weekend'), ('both', 'Both'), ('weekday', 'Weekday')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='catsitter',
            name='available_place',
            field=models.CharField(choices=[('both', 'Both'), ('consignment', 'Consignment'), ('visit', 'Visit')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='catsitter',
            name='available_weekday_time',
            field=models.CharField(choices=[('both', 'Both'), ('pm', 'Pm'), ('am', 'Am')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='catsitter',
            name='available_weekend_time',
            field=models.CharField(choices=[('both', 'Both'), ('pm', 'Pm'), ('am', 'Am')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('form', 'Form'), ('review', 'Review')], max_length=30, null=True),
        ),
    ]
