# Generated by Django 2.1.7 on 2019-07-04 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('takmyo_app', '0017_auto_20190704_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='catsitter',
            name='achievement_rate_per_five',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='catsitter',
            name='achievement_rate_per_hundred',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='catsitter',
            name='kindness_rate_per_five',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='catsitter',
            name='kindness_rate_per_hundred',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='catsitter',
            name='time_rate_per_five',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='catsitter',
            name='time_rate_per_hundred',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='catsitterreview',
            name='catee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catee_reviews', to='takmyo_app.Catee'),
        ),
        migrations.AddField(
            model_name='catsitterreview',
            name='total_rate_per_hundred',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cat',
            name='cat_profile_image',
            field=models.ImageField(blank=True, default='unknown_icon.png', null=True, upload_to='cat_profileImage/None/'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='gender',
            field=models.CharField(default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='cat',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catee_cats', to='takmyo_app.Catee'),
        ),
        migrations.AlterField(
            model_name='catee',
            name='catee_profile_image',
            field=models.ImageField(default='unknown_icon.png', upload_to='catee_profileImage/'),
        ),
        migrations.AlterField(
            model_name='cateetocatsitterform',
            name='catsitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_catsitter_form', to='takmyo_app.Catsitter'),
        ),
        migrations.AlterField(
            model_name='cateetocatsitterform',
            name='state',
            field=models.CharField(choices=[('recognized', 'Recognized'), ('unrecognized', 'Unrecognized'), ('progress', 'Progress')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='catsitter',
            name='available_day',
            field=models.CharField(choices=[('weekend', 'Weekend'), ('both', 'Both'), ('weekday', 'Weekday')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='catsitter',
            name='available_place',
            field=models.CharField(choices=[('consignment', 'Consignment'), ('visit', 'Visit'), ('both', 'Both')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='catsitter',
            name='available_weekday_time',
            field=models.CharField(choices=[('pm', 'Pm'), ('both', 'Both'), ('am', 'Am')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='catsitter',
            name='available_weekend_time',
            field=models.CharField(choices=[('pm', 'Pm'), ('both', 'Both'), ('am', 'Am')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='catsitter',
            name='rate_per_five',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='catsitter',
            name='rate_per_hundred',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='catsitterexperienceimage',
            name='catsitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catsitter_experience_images', to='takmyo_app.Catsitter'),
        ),
        migrations.AlterField(
            model_name='catsitterexperienceimage',
            name='catsitter_experience_image',
            field=models.ImageField(default='unknown_icon.png', upload_to='catsitter_experienceImage/'),
        ),
        migrations.AlterField(
            model_name='catsitterreview',
            name='achievement_rate',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='catsitterreview',
            name='catsitter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catsitter_reviews', to='takmyo_app.Catsitter'),
        ),
        migrations.AlterField(
            model_name='catsitterreview',
            name='kindness_rate',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='catsitterreview',
            name='time_rate',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='catsitterreview',
            name='total_rate',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5),
        ),
    ]
